// Auto-generated by PWA builder script.
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js');

if (workbox) {
    console.log(`Workbox is loaded.`);
    
    self.addEventListener('message', (event) => {
      if (event.data && event.data.type === 'SKIP_WAITING') {
        console.log('Service Worker received SKIP_WAITING message, activating now.');
        self.skipWaiting();
      }
    });

    workbox.precaching.precacheAndRoute([
    {
        "url": "icon-72.png",
        "revision": "d7e2fea916659bbf271b4632f028fed5"
    },
    {
        "url": "icon-96.png",
        "revision": "f1bdf68dd999551760088eb79f5cbcba"
    },
    {
        "url": "icon-128.png",
        "revision": "1ec8980d1a4a78149a5ec7aac0a52a79"
    },
    {
        "url": "icon-144.png",
        "revision": "70839b0a9ce56b64a72ca87b9c29f139"
    },
    {
        "url": "icon-152.png",
        "revision": "24fd20976f6dc6d81b99bdecd571fced"
    },
    {
        "url": "icon-192.png",
        "revision": "286958b45be08bdc916b8e3126b2203d"
    },
    {
        "url": "icon-384.png",
        "revision": "d3d46f60ff5014f7d85d047e1c55329f"
    },
    {
        "url": "icon-512.png",
        "revision": "1a98134a086859d517de611e9e0579bc"
    },
    {
        "url": "favicon.ico",
        "revision": "7cbcf8be98d3ce63133537d07504db0f"
    },
    {
        "url": ".nojekyll",
        "revision": "d41d8cd98f00b204e9800998ecf8427e"
    },
    {
        "url": "allah.mp3",
        "revision": "6ee1fa6162735c9be6314ada3b770627"
    },
    {
        "url": "anthem.mp3",
        "revision": "b97c33069927ab5993e85bb294bc0c05"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates best for html only.pyw",
        "revision": "912a9d55d74613b8f4f07180d0df1fd3"
    },
    {
        "url": "Copy of yasin sketch.png",
        "revision": "558b7e488db001530968b9652f9c8ce0"
    },
    {
        "url": "cv.html",
        "revision": "31a87ef3851cced6d5308db4ae3b3dc5"
    },
    {
        "url": "cv10.html",
        "revision": "9ffee1137c1b76a6618ebe613e04918f"
    },
    {
        "url": "cv11.html",
        "revision": "3758540b35b021b24760bcea146caef8"
    },
    {
        "url": "cv12.html",
        "revision": "55917d7347c5e2e0e44763ad29fedd8a"
    },
    {
        "url": "cv13.html",
        "revision": "541a0a0e3e9dabcd6e866fa414edba1b"
    },
    {
        "url": "cv14.html",
        "revision": "f40d763a947668d42efd3d8220f37f02"
    },
    {
        "url": "cv15.html",
        "revision": "a9e6830a5e983ed10e5b2d6d63ba60bc"
    },
    {
        "url": "cv16.html",
        "revision": "34c9493162824875560ddfab16467bb5"
    },
    {
        "url": "cv17.html",
        "revision": "7edafc3b8d9b42e52399f43bf19c55fd"
    },
    {
        "url": "cv18.html",
        "revision": "a9e6830a5e983ed10e5b2d6d63ba60bc"
    },
    {
        "url": "cv19.html",
        "revision": "420e7bc3ce1276e514e13986b1963f17"
    },
    {
        "url": "cv2.html",
        "revision": "2774849b3c1a0c4c95355e110c302dd5"
    },
    {
        "url": "cv3.html",
        "revision": "c6e1d4cc0637558e22c71b27fb938ae6"
    },
    {
        "url": "cv4.html",
        "revision": "d7f8146a04bda58274b89224599c5b4d"
    },
    {
        "url": "cv5.html",
        "revision": "815fdb9f000315456b400d02ea4b1c11"
    },
    {
        "url": "cv6.html",
        "revision": "8ee3929dc1ff4818d98edcac0ee2d910"
    },
    {
        "url": "cv7.html",
        "revision": "98fa77bf4b8a499095457186b9070003"
    },
    {
        "url": "cv8.html",
        "revision": "44b84e3ee8382b2b780d7665473030e6"
    },
    {
        "url": "cv9.html",
        "revision": "770705ac72d94438f7e44b25812a282f"
    },
    {
        "url": "Duroods.txt",
        "revision": "8c3fb4c453aa5083a1d4a499e5f36a3d"
    },
    {
        "url": "Duroods2.txt",
        "revision": "02cb81e55d14bfa18d76f1b1176f46e5"
    },
    {
        "url": "exp.png",
        "revision": "ebb965ddb6da25270e5c3efbfeeec37f"
    },
    {
        "url": "fb.jpg",
        "revision": "7d57c25d1b28373b2c487c6ca7c8d226"
    },
    {
        "url": "filelist.txt",
        "revision": "52c85d452b2076907eca54f0b0c0b0a4"
    },
    {
        "url": "goldandSilverPrice.html",
        "revision": "efc3a26338cd086f4ce782ae05e2917f"
    },
    {
        "url": "google43faf8d78a699bd4.html",
        "revision": "2dc5557d04f2ac5181bfd5f27cdd7a66"
    },
    {
        "url": "gsap.min.js",
        "revision": "448deef673e4d919eb5592410f72533e"
    },
    {
        "url": "index.html",
        "revision": "df6c51f8ef29a159d43abf2d9c79b4bd"
    },
    {
        "url": "index3.html",
        "revision": "16cfd91d6eb1f939e57942a59cad543d"
    },
    {
        "url": "index4.html",
        "revision": "95cc19d3370f68a3476b953dd21d405f"
    },
    {
        "url": "index5.html",
        "revision": "1ba2ad59f8057749b0f0bfb867248459"
    },
    {
        "url": "index6.html",
        "revision": "dc2470c79675ec0e13bd25132e746b85"
    },
    {
        "url": "indexbk.html",
        "revision": "09a3d03d1509ee1779da3805b11a8c34"
    },
    {
        "url": "indexMsword.html",
        "revision": "9e275ca11644a46ccda31dfabcd2af84"
    },
    {
        "url": "indexonverted.html",
        "revision": "b314c64b581f30a98a2437db4170af35"
    },
    {
        "url": "indexonverted2.html",
        "revision": "e37fde710c8a64cbd19c9fcda46feefb"
    },
    {
        "url": "islam.html",
        "revision": "cd7ddd019e60aa4bac00943d4abc3b07"
    },
    {
        "url": "islam2.html",
        "revision": "aace5eba84fae51e97b913a4e6e010b7"
    },
    {
        "url": "jameel-noori-nastaleeq.ttf",
        "revision": "0feabd6c9714cc4bb922bfb16e1ef20f"
    },
    {
        "url": "jquery-ui.js",
        "revision": "cbc65ff85e08b21d7e0c0394fbf3a371"
    },
    {
        "url": "jquery.html",
        "revision": "d9db2e7eae45ad41a6aaf38f06deedc4"
    },
    {
        "url": "jquery.js",
        "revision": "00727d1d5d9c90f7de826f1a4a9cc632"
    },
    {
        "url": "logo.jpg",
        "revision": "982b8101d5eff0244d33d0cfb47bd0a3"
    },
    {
        "url": "manifest.json",
        "revision": "4d28c91e225e828a46cc07a2d6ffd9af"
    },
    {
        "url": "muhammad(pbuh).html",
        "revision": "48d41cc41b0f01e0a7ea26c1f7646511"
    },
    {
        "url": "muhammad.mp3",
        "revision": "66193d07af6cc74182e19efc10755bca"
    },
    {
        "url": "my yasin picture.png",
        "revision": "38ed966b6f93db56eaa79cd7b4f59f2a"
    },
    {
        "url": "myresume.docx",
        "revision": "c2b72863dafc58559a9175160802e5f3"
    },
    {
        "url": "myresumeold.docx",
        "revision": "ee13bdd6e26b13f25a8386dbe0bd6900"
    },
    {
        "url": "offline.html",
        "revision": "8987c4b748db7cbdf5e4c6165507121b"
    },
    {
        "url": "pak.gif",
        "revision": "0682d2263857f1cc788a8488eecbf76b"
    },
    {
        "url": "prophet.html",
        "revision": "ddd135fbc4b5a81fe872dd7d4aa5dc6a"
    },
    {
        "url": "prophetBirth_1.html",
        "revision": "28c467f8afb82c2204f0144957038693"
    },
    {
        "url": "README.md",
        "revision": "1e7e685ea85ac797c658c9d3ac984b2d"
    },
    {
        "url": "resume.css",
        "revision": "4b5f5640f2b04b8e863242caa6317881"
    },
    {
        "url": "ScrollTrigger.min.js",
        "revision": "9f0592f8748a65b0c765a9dc16e8965f"
    },
    {
        "url": "sitemap.xml",
        "revision": "baa58927a14b5cffd79a5bdbb19302ea"
    },
    {
        "url": "srt.png",
        "revision": "aa922e39d3d85115ce306dd1eeeff653"
    },
    {
        "url": "sw.js",
        "revision": "68089285e59daf71718a1dc8b567af4b"
    },
    {
        "url": "three.min.js",
        "revision": "17ae6ddcbd1d206495dcd2e45508dd1c"
    },
    {
        "url": "ttab.png",
        "revision": "25625b16abc3cc1623bbac0c7322c361"
    },
    {
        "url": "twit.png",
        "revision": "4c6b77a39c06c9670dba1ac6b67940e7"
    },
    {
        "url": "wtsp.jpg",
        "revision": "9c4547952e50513313e52882c2121ade"
    },
    {
        "url": "Yasin new.jpg",
        "revision": "1cc33aef68353599cfd5281f6ad28164"
    },
    {
        "url": "yasin sketch 2.png",
        "revision": "abe0b2aebab7931f37e92debdf7107e2"
    },
    {
        "url": "yasin sketch 3.png",
        "revision": "776bc57086df7b6f0806ab70286b7005"
    },
    {
        "url": "yasin sketch.png",
        "revision": "6b54b2d1ef17f671f03e619d00e15545"
    },
    {
        "url": "Yasin.ico",
        "revision": "49e546550af284d5db439a55f0d1656f"
    },
    {
        "url": "Yasin.jpg",
        "revision": "b6ada0cbd309c0fc5deebc14bd2c79b9"
    },
    {
        "url": "yasin.pdf",
        "revision": "94965e50d9602e7560e54bb1bb16a233"
    },
    {
        "url": "yasin.png",
        "revision": "ad3c315ae393062562f4146432bea831"
    },
    {
        "url": "Yasin2.ico",
        "revision": "4c3c7dba9285eecd68c23b402dbbdd57"
    },
    {
        "url": "Yasin2.png",
        "revision": "0afded513835879a017c8a483d6502dd"
    },
    {
        "url": "yasinOld.jpg",
        "revision": "6c85a524df50b3302269dbfbd630e64f"
    },
    {
        "url": "YasinSearch.HTML",
        "revision": "e10030dea3cecdda2b7b0b86a475e8a2"
    },
    {
        "url": "YasinSearch2.HTML",
        "revision": "6ae631863409d7c2facbee82e7d61585"
    },
    {
        "url": "YasinSearch3.HTML",
        "revision": "881ee62250decf8407fee1cca49f0eec"
    },
    {
        "url": "yt.jpg",
        "revision": "dc5e9de32ee6daf2ddc444f859efc788"
    }
]);

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'style' || request.destination === 'script',
        new workbox.strategies.StaleWhileRevalidate({ cacheName: 'asset-cache' })
    );

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'image',
        new workbox.strategies.CacheFirst({
            cacheName: 'image-cache',
            plugins: [ new workbox.expiration.ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 }) ],
        })
    );

    workbox.routing.setCatchHandler(async ({event}) => {
        if (event.request.destination === 'document') {
            return await caches.match('offline.html') || Response.error();
        }
        return Response.error();
    });

} else {
    console.log(`Workbox failed to load.`);
}